name: Withdraw
main: UniversalRemote\Withdraw
version: "1.0"
api: [1.13.1, 2.0.0, 2.0.1]

commands:
 withdraw:
  permission: withdraw.cmd
  description: Withdraw
  usage: /withdraw <amount>

permissions:
 withdraw.cmd:
  default: true
  description: Withdraw command.
